name = "FoldRNA"
uuid = "c54b6bf2-3650-4185-8b5f-4b1290dd1f68"
authors = ["Marco Matthies <marco.matthies@gmail.com>"]
version = "0.2.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
ViennaRNA_jll = "b7a990de-7fa3-5a2e-8a39-d875e4dafecd"

[compat]
DataStructures = "0.18"
LogExpFunctions = "0.3"
OffsetArrays = "1.12"
ResumableFunctions = "=0.6.5"
StaticArrays = "1.4.4"
Unitful = "1.11"
ViennaRNA_jll = "~2.6.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
